= TodoList RESTful API
made by Park Do Hyun;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

== TodoList(할 일 목록)

할 일을 생성, 조회, 변경, 삭제 할 수 있는 RESTful API 입니다.

[[overview-http-verbs]]
== HTTP 동사

본 RESTful API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스 전체를 수정할 때 사용

| `PATCH`
| 기존 리소스 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 RESTful API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 삭제함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[index]]
== 인덱스

인덱스는 서비스 진입점을 제공합니다.

[[get-index]]
=== 인덱스 조회

`GET` 요청을 사용하여 인덱스에 접근할 수 있다.

operation::get-index[snippets='http-request,http-response,links']

[[create-todo]]
=== 할 일 생성

`POST` 요청을 사용해서 새로운 할 일을 만들 수 있다.

제약조건 ) Title 이 공백일 수 없다.

operation::create-todo[snippets='http-request,request-fields,http-response,response-headers,response-fields,links']

[[get-todo-list]]
=== 할 일 조회(모든 할 일 목록 조회)

`GET` 요청을 사용하여 등록된 모든 할 일 목록을 조회할 수 있다.

operation::get-todo-list[snippets='http-request,http-response,response-fields,links']

[[get-todo-page]]
=== 할 일 조회(할 일 목록 페이지 단위로 조회)

`GET` 요청을 사용하여 등록된 할 일 목록을 페에지 단위로 조회할 수 있다.

operation::get-todo-page[snippets='http-request,http-response,response-fields,links']

[[get-todo]]
=== 할 일 조회(하나의 할 일 조회)

`Get` 요청을 사용해서 등록된 할 일 하나를 조회할 수 있다.

operation::get-todo[snippets='http-request,http-response,response-fields,links']

[[modify-todo]]
=== 할 일 수정

`PUT` 요청을 사용해서 등록된 할 일을 수정할 수 있다.

제약조건 1 ) Title 이 공백일 수 없다.

제약조건 2 ) 이미 종료된 할 일은 수정할 수 없다.

operation::modify-todo[snippets='http-request,request-fields,http-response,response-fields,links']

[[finish-todo]]
=== 할 일 종료

`PATCH` 요청을 사용해서 등록된 할 일을 종료시킬 수 있다.

operation::finish-todo[snippets='http-request,http-response,response-fields,links']

[[delete-all-todos]]
=== 할 일 삭제(모든 할 일 삭제)

`DELETE` 요청을 사용해서 모든 할 일을 삭제할 수 있다.

operation::delete-all-todos[snippets='http-request,http-response,links']

[[delete-todo]]
=== 할 일 삭제(하나의 할 일 삭제)

`DELETE` 요청을 사용해서 등록된 할 일을 삭제할 수 있다.

operation::delete-todo[snippets='http-request,http-response,links']
